version: '3.8'

services:
  # Webserver Container
  web-container:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@database-container:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@database-container:5432/web_test
    depends_on:
      - database-container

  # Database Contanier
  database-container:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
